#!/bin/sh

case "$1" in
    start)
	echo "load scull module"
	/usr/bin/scull_load
	;;
    stop)
	echo "unload scull module"
	/usr/bin/scull_unload
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
